### ISSUE TITLE
Tasks for the TIDs v2

### ISSUE THREAD

**Issue by pescap** [pescap/EasyHPC#84]
Hi, as we are going very slow, I suggest to close tasks one by one. Here are the tasks for each one, with higher priority.

Before April 21st:
- [x] @Ehaw04: Finish PR #81. 
- [x]  @ArtemioA: Finish Issue #66 
- [x] @Setol21: Send a PR to close #50
- [x]  @agustinesoto : Send a PR to close #46  

Before April 26th:
- [x] @Ehaw04 fix WSL issue (re-install?)
- [x] @agustinesoto @Setol21: Close https://github.com/pescap/FastDeepXDE/issues/3 

Before May 3rd:
- [x] @ArtemioA Close https://github.com/pescap/EasyHPC/issues/52
- [x] @ArtemioA @Ehaw04 Close https://github.com/pescap/ScattPINNs/issues/7

Before May 5th:
- [x] @ArtemioA @Ehaw04 Close https://github.com/pescap/ScattPINNs/issues/8

Before May 12th:
- [x] @Setol21: Close https://github.com/pescap/FastDeepXDE/issues/3 
- [ ] @ArtemioA: Close https://github.com/pescap/EasyHPC/issues/87

End of May: 
- [ ] @Ehaw04 @ArtemioA: Close #69

**Comment by ArtemioA** [comment]
![image](https://user-images.githubusercontent.com/78178128/164956814-2db31c92-96ab-4852-948c-1c14da700930.png)

Professor,
why i have this problem when i try to use deepxde (import deepxde as dde)?

**Comment by ArtemioA** [comment]
![image](https://user-images.githubusercontent.com/78178128/164957234-a800e209-225f-4b92-8a42-540244ec685e.png)

Working!!

**Comment by Ehaw04** [comment]
![uwa](https://user-images.githubusercontent.com/101342356/165010643-96c84523-da93-47ad-94df-05b76fbd7457.png)

ubuntu working again!!
